apiVersion: v1
kind: Pod
metadata:
  name: folding
spec:
  containers:
  - name: foldingathome
    image: lscr.io/linuxserver/foldingathome:latest
    ports:
    - containerPort: 7396
    volumeMounts:
    - name: storage
      mountPath: /config
    env:
    - name: PUID
      value: 1000
    - name: PGID
      value: 1000 
    - name: ACCOUNT_TOKEN
      value: Ly0UQLyyLKGcSLKKUaDY6UaNEj9v9EjyZlqtSZl0yQc
    - name: MACHINE_NAME
      value: "kubernetes machine"
    - name: TZ
      value: "Etc/UTC"
  volumes:
  - name: storage
    emptyDir: {}